Add onExpand callback
reduxjs/redux-devtools pull request #683
Opened 2020-11-20 23:49 UTC by balinaanna

2020-12-22 16:19 UTC, Methuselah96 requested changes
Thanks for the PR! Looks like there's a lint error and you need to run `yarn prettify` in the top-most directory in order for the build to pass.

2020-12-22 16:19 UTC, Methuselah96 commented
Also, could you an `onCollapse` as well while you're at it?

2023-06-21 10:55 UTC, Attyuttam commented
are we planning to incorporate this change anytime soon ?

2025-06-07 18:18 UTC, rpk-red commented
Any news on this one?

2026-09-19 23:57 UTC, closed without merging